// Code generated by protoc-gen-go.
// source: friend_list.proto
// DO NOT EDIT!

package vo

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type FriendListRequest struct {
}

func (m *FriendListRequest) Reset()         { *m = FriendListRequest{} }
func (m *FriendListRequest) String() string { return proto.CompactTextString(m) }
func (*FriendListRequest) ProtoMessage()    {}

type FriendListResponse struct {
	StatusCode int32   `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	StatusMsg  string  `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg" json:"status_msg,omitempty"`
	Friends    []*User `protobuf:"bytes,3,rep,name=friends" json:"friends,omitempty"`
	TotalNum   int32   `protobuf:"varint,4,opt,name=total_num,json=totalNum" json:"total_num,omitempty"`
}

func (m *FriendListResponse) Reset()         { *m = FriendListResponse{} }
func (m *FriendListResponse) String() string { return proto.CompactTextString(m) }
func (*FriendListResponse) ProtoMessage()    {}

func (m *FriendListResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *FriendListResponse) GetStatusMsg() string {
	if m != nil {
		return m.StatusMsg
	}
	return ""
}

func (m *FriendListResponse) GetFriends() []*User {
	if m != nil {
		return m.Friends
	}
	return nil
}

func (m *FriendListResponse) GetTotalNum() int32 {
	if m != nil {
		return m.TotalNum
	}
	return 0
}
