// Code generated by protoc-gen-go.
// source: group_search.proto
// DO NOT EDIT!

package vo

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type GroupSearchRequest struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Page     int32  `protobuf:"varint,2,opt,name=page" json:"page,omitempty"`
	PageSize int32  `protobuf:"varint,3,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
}

func (m *GroupSearchRequest) Reset()         { *m = GroupSearchRequest{} }
func (m *GroupSearchRequest) String() string { return proto.CompactTextString(m) }
func (*GroupSearchRequest) ProtoMessage()    {}

func (m *GroupSearchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GroupSearchRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GroupSearchRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type GroupSearchResponse struct {
	StatusCode int32        `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	StatusMsg  string       `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg" json:"status_msg,omitempty"`
	Groups     []*GroupInfo `protobuf:"bytes,3,rep,name=groups" json:"groups,omitempty"`
	TotalNum   int32        `protobuf:"varint,4,opt,name=total_num,json=totalNum" json:"total_num,omitempty"`
}

func (m *GroupSearchResponse) Reset()         { *m = GroupSearchResponse{} }
func (m *GroupSearchResponse) String() string { return proto.CompactTextString(m) }
func (*GroupSearchResponse) ProtoMessage()    {}

func (m *GroupSearchResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *GroupSearchResponse) GetStatusMsg() string {
	if m != nil {
		return m.StatusMsg
	}
	return ""
}

func (m *GroupSearchResponse) GetGroups() []*GroupInfo {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *GroupSearchResponse) GetTotalNum() int32 {
	if m != nil {
		return m.TotalNum
	}
	return 0
}
