// Code generated by protoc-gen-go.
// source: group_member_list.proto
// DO NOT EDIT!

package vo

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type GroupMemberListRequest struct {
	GroupId int64 `protobuf:"varint,1,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
}

func (m *GroupMemberListRequest) Reset()         { *m = GroupMemberListRequest{} }
func (m *GroupMemberListRequest) String() string { return proto.CompactTextString(m) }
func (*GroupMemberListRequest) ProtoMessage()    {}

func (m *GroupMemberListRequest) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

type GroupMemberListResponse struct {
	StatusCode int32          `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	StatusMsg  string         `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg" json:"status_msg,omitempty"`
	Members    []*GroupMember `protobuf:"bytes,3,rep,name=members" json:"members,omitempty"`
}

func (m *GroupMemberListResponse) Reset()         { *m = GroupMemberListResponse{} }
func (m *GroupMemberListResponse) String() string { return proto.CompactTextString(m) }
func (*GroupMemberListResponse) ProtoMessage()    {}

func (m *GroupMemberListResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *GroupMemberListResponse) GetStatusMsg() string {
	if m != nil {
		return m.StatusMsg
	}
	return ""
}

func (m *GroupMemberListResponse) GetMembers() []*GroupMember {
	if m != nil {
		return m.Members
	}
	return nil
}
