// Code generated by protoc-gen-go.
// source: message_search.proto
// DO NOT EDIT!

package vo

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type MessageSearchRequest struct {
	Receiver       int64  `protobuf:"varint,1,opt,name=receiver" json:"receiver,omitempty"`
	Cursor         string `protobuf:"bytes,2,opt,name=cursor" json:"cursor,omitempty"`
	Count          int32  `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	ConversationId string `protobuf:"bytes,4,opt,name=conversation_id,json=conversationId" json:"conversation_id,omitempty"`
}

func (m *MessageSearchRequest) Reset()         { *m = MessageSearchRequest{} }
func (m *MessageSearchRequest) String() string { return proto.CompactTextString(m) }
func (*MessageSearchRequest) ProtoMessage()    {}

func (m *MessageSearchRequest) GetReceiver() int64 {
	if m != nil {
		return m.Receiver
	}
	return 0
}

func (m *MessageSearchRequest) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

func (m *MessageSearchRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *MessageSearchRequest) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

type MessageSearchResponse struct {
	StatusCode  int32          `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	StatusMsg   string         `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg" json:"status_msg,omitempty"`
	MessageList []*MessageBody `protobuf:"bytes,3,rep,name=message_list,json=messageList" json:"message_list,omitempty"`
	Cursor      string         `protobuf:"bytes,4,opt,name=cursor" json:"cursor,omitempty"`
	HasMore     bool           `protobuf:"varint,5,opt,name=has_more,json=hasMore" json:"has_more,omitempty"`
}

func (m *MessageSearchResponse) Reset()         { *m = MessageSearchResponse{} }
func (m *MessageSearchResponse) String() string { return proto.CompactTextString(m) }
func (*MessageSearchResponse) ProtoMessage()    {}

func (m *MessageSearchResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *MessageSearchResponse) GetStatusMsg() string {
	if m != nil {
		return m.StatusMsg
	}
	return ""
}

func (m *MessageSearchResponse) GetMessageList() []*MessageBody {
	if m != nil {
		return m.MessageList
	}
	return nil
}

func (m *MessageSearchResponse) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

func (m *MessageSearchResponse) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}
