// Code generated by protoc-gen-go.
// source: message_pull.proto
// DO NOT EDIT!

package vo

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type MessagePullRequest struct {
	Receiver         int64  `protobuf:"varint,1,opt,name=receiver" json:"receiver,omitempty"`
	Cursor           int64  `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
	Count            int32  `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	ConversationId   string `protobuf:"bytes,4,opt,name=conversation_id,json=conversationId" json:"conversation_id,omitempty"`
	ConversationType int32  `protobuf:"varint,5,opt,name=conversation_type,json=conversationType" json:"conversation_type,omitempty"`
	InboxType        int32  `protobuf:"varint,6,opt,name=inbox_type,json=inboxType" json:"inbox_type,omitempty"`
	MsgIdStr         string `protobuf:"bytes,7,opt,name=msg_id_str,json=msgIdStr" json:"msg_id_str,omitempty"`
}

func (m *MessagePullRequest) Reset()         { *m = MessagePullRequest{} }
func (m *MessagePullRequest) String() string { return proto.CompactTextString(m) }
func (*MessagePullRequest) ProtoMessage()    {}

func (m *MessagePullRequest) GetReceiver() int64 {
	if m != nil {
		return m.Receiver
	}
	return 0
}

func (m *MessagePullRequest) GetCursor() int64 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

func (m *MessagePullRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *MessagePullRequest) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

func (m *MessagePullRequest) GetConversationType() int32 {
	if m != nil {
		return m.ConversationType
	}
	return 0
}

func (m *MessagePullRequest) GetInboxType() int32 {
	if m != nil {
		return m.InboxType
	}
	return 0
}

func (m *MessagePullRequest) GetMsgIdStr() string {
	if m != nil {
		return m.MsgIdStr
	}
	return ""
}

type MessagePullResponse struct {
	StatusCode  int32          `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	StatusMsg   string         `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg" json:"status_msg,omitempty"`
	MessageList []*MessageBody `protobuf:"bytes,3,rep,name=message_list,json=messageList" json:"message_list,omitempty"`
	Cursor      int64          `protobuf:"varint,4,opt,name=cursor" json:"cursor,omitempty"`
	HasMore     bool           `protobuf:"varint,5,opt,name=has_more,json=hasMore" json:"has_more,omitempty"`
}

func (m *MessagePullResponse) Reset()         { *m = MessagePullResponse{} }
func (m *MessagePullResponse) String() string { return proto.CompactTextString(m) }
func (*MessagePullResponse) ProtoMessage()    {}

func (m *MessagePullResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *MessagePullResponse) GetStatusMsg() string {
	if m != nil {
		return m.StatusMsg
	}
	return ""
}

func (m *MessagePullResponse) GetMessageList() []*MessageBody {
	if m != nil {
		return m.MessageList
	}
	return nil
}

func (m *MessagePullResponse) GetCursor() int64 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

func (m *MessagePullResponse) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}
