// Code generated by protoc-gen-go.
// source: message_send.proto
// DO NOT EDIT!

package vo

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type MessageSendRequest struct {
	Sender           int64             `protobuf:"varint,1,opt,name=sender" json:"sender,omitempty"`
	Receiver         int64             `protobuf:"varint,2,opt,name=receiver" json:"receiver,omitempty"`
	InboxType        int32             `protobuf:"varint,3,opt,name=inbox_type,json=inboxType" json:"inbox_type,omitempty"`
	ConversationType int32             `protobuf:"varint,4,opt,name=conversation_type,json=conversationType" json:"conversation_type,omitempty"`
	ConversationId   string            `protobuf:"bytes,5,opt,name=conversation_id,json=conversationId" json:"conversation_id,omitempty"`
	MsgType          int32             `protobuf:"varint,6,opt,name=msg_type,json=msgType" json:"msg_type,omitempty"`
	Content          string            `protobuf:"bytes,7,opt,name=content" json:"content,omitempty"`
	Ext              map[string]string `protobuf:"bytes,8,rep,name=ext" json:"ext,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *MessageSendRequest) Reset()         { *m = MessageSendRequest{} }
func (m *MessageSendRequest) String() string { return proto.CompactTextString(m) }
func (*MessageSendRequest) ProtoMessage()    {}

func (m *MessageSendRequest) GetSender() int64 {
	if m != nil {
		return m.Sender
	}
	return 0
}

func (m *MessageSendRequest) GetReceiver() int64 {
	if m != nil {
		return m.Receiver
	}
	return 0
}

func (m *MessageSendRequest) GetInboxType() int32 {
	if m != nil {
		return m.InboxType
	}
	return 0
}

func (m *MessageSendRequest) GetConversationType() int32 {
	if m != nil {
		return m.ConversationType
	}
	return 0
}

func (m *MessageSendRequest) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

func (m *MessageSendRequest) GetMsgType() int32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *MessageSendRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MessageSendRequest) GetExt() map[string]string {
	if m != nil {
		return m.Ext
	}
	return nil
}

type MessageSendResponse struct {
	StatusCode int32  `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	StatusMsg  string `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg" json:"status_msg,omitempty"`
	MsgId      int64  `protobuf:"varint,3,opt,name=msg_id,json=msgId" json:"msg_id,omitempty"`
}

func (m *MessageSendResponse) Reset()         { *m = MessageSendResponse{} }
func (m *MessageSendResponse) String() string { return proto.CompactTextString(m) }
func (*MessageSendResponse) ProtoMessage()    {}

func (m *MessageSendResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *MessageSendResponse) GetStatusMsg() string {
	if m != nil {
		return m.StatusMsg
	}
	return ""
}

func (m *MessageSendResponse) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}
