// Code generated by protoc-gen-go.
// source: relation_apply_create.proto
// DO NOT EDIT!

package vo

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type RelationApplyCreateRequest struct {
	ToUserId  int64 `protobuf:"varint,1,opt,name=to_user_id,json=toUserId" json:"to_user_id,omitempty"`
	ApplyType int32 `protobuf:"varint,2,opt,name=apply_type,json=applyType" json:"apply_type,omitempty"`
}

func (m *RelationApplyCreateRequest) Reset()         { *m = RelationApplyCreateRequest{} }
func (m *RelationApplyCreateRequest) String() string { return proto.CompactTextString(m) }
func (*RelationApplyCreateRequest) ProtoMessage()    {}

func (m *RelationApplyCreateRequest) GetToUserId() int64 {
	if m != nil {
		return m.ToUserId
	}
	return 0
}

func (m *RelationApplyCreateRequest) GetApplyType() int32 {
	if m != nil {
		return m.ApplyType
	}
	return 0
}

type RelationApplyCreateResponse struct {
	StatusCode int32  `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	StatusMsg  string `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg" json:"status_msg,omitempty"`
	ApplyId    int64  `protobuf:"varint,3,opt,name=apply_id,json=applyId" json:"apply_id,omitempty"`
}

func (m *RelationApplyCreateResponse) Reset()         { *m = RelationApplyCreateResponse{} }
func (m *RelationApplyCreateResponse) String() string { return proto.CompactTextString(m) }
func (*RelationApplyCreateResponse) ProtoMessage()    {}

func (m *RelationApplyCreateResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RelationApplyCreateResponse) GetStatusMsg() string {
	if m != nil {
		return m.StatusMsg
	}
	return ""
}

func (m *RelationApplyCreateResponse) GetApplyId() int64 {
	if m != nil {
		return m.ApplyId
	}
	return 0
}
