// Code generated by protoc-gen-go.
// source: relation_apply_list.proto
// DO NOT EDIT!

package vo

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type RelationApplyListRequest struct {
	ApplyType  int32   `protobuf:"varint,1,opt,name=apply_type,json=applyType" json:"apply_type,omitempty"`
	StatusList []int32 `protobuf:"varint,2,rep,packed,name=status_list,json=statusList" json:"status_list,omitempty"`
	Page       int32   `protobuf:"varint,3,opt,name=page" json:"page,omitempty"`
	PageSize   int32   `protobuf:"varint,4,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
}

func (m *RelationApplyListRequest) Reset()         { *m = RelationApplyListRequest{} }
func (m *RelationApplyListRequest) String() string { return proto.CompactTextString(m) }
func (*RelationApplyListRequest) ProtoMessage()    {}

func (m *RelationApplyListRequest) GetApplyType() int32 {
	if m != nil {
		return m.ApplyType
	}
	return 0
}

func (m *RelationApplyListRequest) GetStatusList() []int32 {
	if m != nil {
		return m.StatusList
	}
	return nil
}

func (m *RelationApplyListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *RelationApplyListRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type RelationApplyListResponse struct {
	StatusCode int32            `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	StatusMsg  string           `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg" json:"status_msg,omitempty"`
	ApplyList  []*RelationApply `protobuf:"bytes,3,rep,name=apply_list,json=applyList" json:"apply_list,omitempty"`
	TotalNum   int32            `protobuf:"varint,4,opt,name=total_num,json=totalNum" json:"total_num,omitempty"`
}

func (m *RelationApplyListResponse) Reset()         { *m = RelationApplyListResponse{} }
func (m *RelationApplyListResponse) String() string { return proto.CompactTextString(m) }
func (*RelationApplyListResponse) ProtoMessage()    {}

func (m *RelationApplyListResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RelationApplyListResponse) GetStatusMsg() string {
	if m != nil {
		return m.StatusMsg
	}
	return ""
}

func (m *RelationApplyListResponse) GetApplyList() []*RelationApply {
	if m != nil {
		return m.ApplyList
	}
	return nil
}

func (m *RelationApplyListResponse) GetTotalNum() int32 {
	if m != nil {
		return m.TotalNum
	}
	return 0
}
