// Code generated by protoc-gen-go.
// source: relation_apply_update.proto
// DO NOT EDIT!

package vo

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type RelationApplyUpdateRequest struct {
	ApplyId int64 `protobuf:"varint,1,opt,name=apply_id,json=applyId" json:"apply_id,omitempty"`
	Status  int32 `protobuf:"varint,2,opt,name=status" json:"status,omitempty"`
}

func (m *RelationApplyUpdateRequest) Reset()         { *m = RelationApplyUpdateRequest{} }
func (m *RelationApplyUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*RelationApplyUpdateRequest) ProtoMessage()    {}

func (m *RelationApplyUpdateRequest) GetApplyId() int64 {
	if m != nil {
		return m.ApplyId
	}
	return 0
}

func (m *RelationApplyUpdateRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type RelationApplyUpdateResponse struct {
	StatusCode int32  `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	StatusMsg  string `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg" json:"status_msg,omitempty"`
}

func (m *RelationApplyUpdateResponse) Reset()         { *m = RelationApplyUpdateResponse{} }
func (m *RelationApplyUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*RelationApplyUpdateResponse) ProtoMessage()    {}

func (m *RelationApplyUpdateResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RelationApplyUpdateResponse) GetStatusMsg() string {
	if m != nil {
		return m.StatusMsg
	}
	return ""
}
