// Code generated by protoc-gen-go.
// source: user_search.proto
// DO NOT EDIT!

package vo

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type UserSearchRequest struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Page     int32  `protobuf:"varint,2,opt,name=page" json:"page,omitempty"`
	PageSize int32  `protobuf:"varint,3,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
}

func (m *UserSearchRequest) Reset()         { *m = UserSearchRequest{} }
func (m *UserSearchRequest) String() string { return proto.CompactTextString(m) }
func (*UserSearchRequest) ProtoMessage()    {}

func (m *UserSearchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserSearchRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *UserSearchRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type UserSearchResponse struct {
	StatusCode int32   `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	StatusMsg  string  `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg" json:"status_msg,omitempty"`
	UserInfo   []*User `protobuf:"bytes,3,rep,name=user_info,json=userInfo" json:"user_info,omitempty"`
	TotalNum   int32   `protobuf:"varint,4,opt,name=total_num,json=totalNum" json:"total_num,omitempty"`
}

func (m *UserSearchResponse) Reset()         { *m = UserSearchResponse{} }
func (m *UserSearchResponse) String() string { return proto.CompactTextString(m) }
func (*UserSearchResponse) ProtoMessage()    {}

func (m *UserSearchResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *UserSearchResponse) GetStatusMsg() string {
	if m != nil {
		return m.StatusMsg
	}
	return ""
}

func (m *UserSearchResponse) GetUserInfo() []*User {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *UserSearchResponse) GetTotalNum() int32 {
	if m != nil {
		return m.TotalNum
	}
	return 0
}
